# Generated by Django 3.0.8 on 2020-07-19 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acccounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
    ]
